/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry_Username;
  GtkWidget *entry_Password;
  GtkWidget *image2;
  GtkWidget *YZ_Login;
  GtkWidget *YZ_Mot_de_passe;
  GtkWidget *image1;
  GtkWidget *button1;
  GtkWidget *alignment16;
  GtkWidget *hbox12;
  GtkWidget *image53;
  GtkWidget *label49;
  GtkWidget *YZ_Authentication;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry_Username = gtk_entry_new ();
  gtk_widget_show (entry_Username);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_Username, 136, 104);
  gtk_widget_set_size_request (entry_Username, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Username), 8226);

  entry_Password = gtk_entry_new ();
  gtk_widget_show (entry_Password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_Password, 136, 144);
  gtk_widget_set_size_request (entry_Password, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Password), 8226);

  image2 = create_pixmap (window1, "Firefox_wallpaper.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1), image2, 0, 0);
  gtk_widget_set_size_request (image2, 432, 72);

  YZ_Login = gtk_label_new (_("Login"));
  gtk_widget_show (YZ_Login);
  gtk_fixed_put (GTK_FIXED (fixed1), YZ_Login, 64, 112);
  gtk_widget_set_size_request (YZ_Login, 64, 16);

  YZ_Mot_de_passe = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (YZ_Mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed1), YZ_Mot_de_passe, 16, 152);
  gtk_widget_set_size_request (YZ_Mot_de_passe, 136, 16);

  image1 = create_pixmap (window1, "Firefox_wallpaper.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 232);
  gtk_widget_set_size_request (image1, 432, 88);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 152, 184);
  gtk_widget_set_size_request (button1, 120, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button1), alignment16);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox12);

  image53 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox12), image53, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\">  Connecter</span>"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox12), label49, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  YZ_Authentication = gtk_label_new (_("<span foreground=\"black\">Authentification</span>"));
  gtk_widget_show (YZ_Authentication);
  gtk_fixed_put (GTK_FIXED (fixed1), YZ_Authentication, 152, 80);
  gtk_widget_set_size_request (YZ_Authentication, 128, 16);
  gtk_label_set_use_markup (GTK_LABEL (YZ_Authentication), TRUE);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry_Username, "entry_Username");
  GLADE_HOOKUP_OBJECT (window1, entry_Password, "entry_Password");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, YZ_Login, "YZ_Login");
  GLADE_HOOKUP_OBJECT (window1, YZ_Mot_de_passe, "YZ_Mot_de_passe");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image53, "image53");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, YZ_Authentication, "YZ_Authentication");

  return window1;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *treeview_service;
  GtkWidget *entry3;
  GtkWidget *image8;
  GtkWidget *Yz_ID_service;
  GtkWidget *button16;
  GtkWidget *alignment31;
  GtkWidget *hbox27;
  GtkWidget *image73;
  GtkWidget *label70;
  GtkWidget *image15;
  GtkWidget *image12;
  GtkWidget *image13;
  GtkWidget *button3;
  GtkWidget *alignment30;
  GtkWidget *hbox26;
  GtkWidget *image72;
  GtkWidget *label69;
  GtkWidget *button4;
  GtkWidget *alignment19;
  GtkWidget *hbox15;
  GtkWidget *image56;
  GtkWidget *label52;
  GtkWidget *button2;
  GtkWidget *alignment17;
  GtkWidget *hbox13;
  GtkWidget *image54;
  GtkWidget *label50;
  GtkWidget *button5;
  GtkWidget *alignment20;
  GtkWidget *hbox16;
  GtkWidget *image57;
  GtkWidget *label53;
  GtkWidget *image78;
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed5;
  GtkWidget *alignment5;
  GtkWidget *combobox1;
  GtkObject *spinButton_place_adj;
  GtkWidget *spinButton_place;
  GtkWidget *entry_id_service;
  GtkWidget *entry_matricule;
  GtkWidget *alignment6;
  GtkWidget *combobox2;
  GtkWidget *YZ_label19;
  GtkWidget *YZ_label20;
  GtkWidget *YZ_label22;
  GtkWidget *YZ_radiobutton2;
  GSList *YZ_radiobutton2_group = NULL;
  GtkWidget *YZ_radiobutton1;
  GtkWidget *image19;
  GtkWidget *image75;
  GtkWidget *YZ_checkbutton1;
  GtkWidget *YZ_checkbutton2;
  GtkWidget *image16;
  GtkWidget *YZ_label18;
  GtkWidget *image22;
  GtkWidget *YZ_label23;
  GtkWidget *YZ_label21;
  GtkWidget *image77;
  GtkWidget *image20;
  GtkWidget *button6;
  GtkWidget *alignment21;
  GtkWidget *hbox17;
  GtkWidget *image58;
  GtkWidget *label54;
  GtkWidget *image21;
  GtkWidget *button14;
  GtkWidget *alignment29;
  GtkWidget *hbox25;
  GtkWidget *image66;
  GtkWidget *label68;
  GtkWidget *YZ_label8;
  GtkWidget *fixed8;
  GtkWidget *entry_id_service3;
  GtkWidget *image30;
  GtkWidget *image33;
  GtkWidget *YZ_label35;
  GtkWidget *image32;
  GtkWidget *YZ_label32;
  GtkWidget *button15;
  GtkWidget *image71;
  GtkWidget *image31;
  GtkWidget *image34;
  GtkWidget *YZ_label9;
  GtkWidget *fixed7;
  GtkWidget *entry_id_service1;
  GtkWidget *image23;
  GtkWidget *eventbox1;
  GtkWidget *combobox3;
  GtkWidget *entry_matricule1;
  GtkWidget *YZ_label26;
  GtkWidget *YZ_label27;
  GtkWidget *YZ_label28;
  GtkWidget *eventbox2;
  GtkWidget *combobox4;
  GtkWidget *alignment9;
  GtkObject *spinButton_place2_adj;
  GtkWidget *spinButton_place2;
  GtkWidget *YZ_label25;
  GtkWidget *YZ_label29;
  GtkWidget *image28;
  GtkWidget *button17;
  GtkWidget *alignment32;
  GtkWidget *hbox28;
  GtkWidget *image74;
  GtkWidget *label71;
  GtkWidget *button8;
  GtkWidget *alignment23;
  GtkWidget *hbox19;
  GtkWidget *image60;
  GtkWidget *label56;
  GtkWidget *image25;
  GtkWidget *YZ_label31;
  GtkWidget *image29;
  GtkWidget *image76;
  GtkWidget *image27;
  GtkWidget *checkbutton3;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *checkbutton4;
  GtkWidget *image26;
  GtkWidget *button18;
  GtkWidget *alignment33;
  GtkWidget *hbox29;
  GtkWidget *image79;
  GtkWidget *label72;
  GtkWidget *fenetre_ajout;
  GtkWidget *fixed9;
  GtkWidget *YZ_entry11;
  GtkWidget *eventbox3;
  GtkWidget *combobox5;
  GtkWidget *button10;
  GtkWidget *alignment25;
  GtkWidget *hbox21;
  GtkWidget *image62;
  GtkWidget *label58;
  GtkWidget *YZ_label37;
  GtkWidget *image44;
  GtkWidget *YZ_label39;
  GtkWidget *image45;
  GtkWidget *image39;
  GtkWidget *image47;
  GtkWidget *image46;
  GtkWidget *image36;
  GtkWidget *YZ_label36;
  GtkWidget *YZ_label11;
  GtkWidget *fixed10;
  GtkWidget *YZ_entry12;
  GtkWidget *YZ_entry13;
  GtkWidget *button12;
  GtkWidget *alignment27;
  GtkWidget *hbox23;
  GtkWidget *image64;
  GtkWidget *label60;
  GtkWidget *button11;
  GtkWidget *alignment26;
  GtkWidget *hbox22;
  GtkWidget *image63;
  GtkWidget *label59;
  GtkWidget *image50;
  GtkWidget *image51;
  GtkWidget *image43;
  GtkWidget *YZ_label45;
  GtkWidget *image49;
  GtkWidget *image48;
  GtkWidget *lYZ_abel44;
  GtkWidget *image40;
  GtkWidget *YZ_label42;
  GtkWidget *YZ_label12;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 592, 720);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview_service = gtk_tree_view_new ();
  gtk_widget_show (treeview_service);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview_service, 120, 112);
  gtk_widget_set_size_request (treeview_service, 400, 320);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 208, 72);
  gtk_widget_set_size_request (entry3, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  image8 = gtk_image_new_from_icon_name ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed4), image8, 120, 80);
  gtk_widget_set_size_request (image8, 21, 21);

  Yz_ID_service = gtk_label_new (_("ID service"));
  gtk_widget_show (Yz_ID_service);
  gtk_fixed_put (GTK_FIXED (fixed4), Yz_ID_service, 104, 80);
  gtk_widget_set_size_request (Yz_ID_service, 141, 17);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed4), button16, 136, 480);
  gtk_widget_set_size_request (button16, 104, 40);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button16), alignment31);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox27);

  image73 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image73);
  gtk_box_pack_start (GTK_BOX (hbox27), image73, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox27), label70, FALSE, FALSE, 0);

  image15 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed4), image15, 112, 0);
  gtk_widget_set_size_request (image15, 416, 64);

  image12 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed4), image12, -24, 0);
  gtk_widget_set_size_request (image12, 136, 560);

  image13 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed4), image13, 520, 0);
  gtk_widget_set_size_request (image13, 120, 560);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 408, 520);
  gtk_widget_set_size_request (button3, 104, 32);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button3), alignment30);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox26);

  image72 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image72);
  gtk_box_pack_start (GTK_BOX (hbox26), image72, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox26), label69, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 408, 456);
  gtk_widget_set_size_request (button4, 104, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button4), alignment19);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox15);

  image56 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox15), image56, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox15), label52, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 408, 72);
  gtk_widget_set_size_request (button2, 106, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button2), alignment17);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox13);

  image54 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox13), image54, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox13), label50, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 408, 488);
  gtk_widget_set_size_request (button5, 104, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button5), alignment20);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox16);

  image57 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox16), image57, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("R\303\251frecher"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox16), label53, FALSE, FALSE, 0);

  image78 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image78);
  gtk_fixed_put (GTK_FIXED (fixed4), image78, -8, 560);
  gtk_widget_set_size_request (image78, 608, 152);

  fenetre_afficher = gtk_label_new (_("<span foreground=\"royalblue\" weight=\"bold\" size=\"12000\">Afficher</span>"));
  gtk_widget_show (fenetre_afficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), fenetre_afficher);
  gtk_label_set_use_markup (GTK_LABEL (fenetre_afficher), TRUE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment5, 208, 160);
  gtk_widget_set_size_request (alignment5, 234, 41);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_container_add (GTK_CONTAINER (alignment5), combobox1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Voiture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Velo "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Moto"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("scooters"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Autobus"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("caravanes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bicycles_et_scooter_\303\251lectriques"));

  spinButton_place_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinButton_place = gtk_spin_button_new (GTK_ADJUSTMENT (spinButton_place_adj), 1, 0);
  gtk_widget_show (spinButton_place);
  gtk_fixed_put (GTK_FIXED (fixed5), spinButton_place, 280, 232);
  gtk_widget_set_size_request (spinButton_place, 96, 32);

  entry_id_service = gtk_entry_new ();
  gtk_widget_show (entry_id_service);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_id_service, 160, 88);
  gtk_widget_set_size_request (entry_id_service, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service), 8226);

  entry_matricule = gtk_entry_new ();
  gtk_widget_show (entry_matricule);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_matricule, 176, 288);
  gtk_widget_set_size_request (entry_matricule, 304, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_matricule), 8226);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment6);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment6, 216, 360);
  gtk_widget_set_size_request (alignment6, 235, 43);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_container_add (GTK_CONTAINER (alignment6), combobox2);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Borne_de_chage_\303\251l\303\251ctrique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Lavage "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Maintenance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("S\303\251curit\303\251_et_surveillance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Services_de_valet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Espace_covoiturage"));

  YZ_label19 = gtk_label_new (_("Types de transport"));
  gtk_widget_show (YZ_label19);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label19, 32, 176);
  gtk_widget_set_size_request (YZ_label19, 205, 17);

  YZ_label20 = gtk_label_new (_("Numero de place "));
  gtk_widget_show (YZ_label20);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label20, 96, 240);
  gtk_widget_set_size_request (YZ_label20, 184, 17);

  YZ_label22 = gtk_label_new (_("Type de service"));
  gtk_widget_show (YZ_label22);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label22, 72, 376);
  gtk_widget_set_size_request (YZ_label22, 159, 17);

  YZ_radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Normal"));
  gtk_widget_show (YZ_radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_radiobutton2, 352, 448);
  gtk_widget_set_size_request (YZ_radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (YZ_radiobutton2), YZ_radiobutton2_group);
  YZ_radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (YZ_radiobutton2));

  YZ_radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Premium"));
  gtk_widget_show (YZ_radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_radiobutton1, 200, 448);
  gtk_widget_set_size_request (YZ_radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (YZ_radiobutton1), YZ_radiobutton2_group);
  YZ_radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (YZ_radiobutton1));

  image19 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed5), image19, -8, 592);
  gtk_widget_set_size_request (image19, 656, 120);

  image75 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image75);
  gtk_fixed_put (GTK_FIXED (fixed5), image75, 608, 40);
  gtk_widget_set_size_request (image75, 40, 552);

  YZ_checkbutton1 = gtk_check_button_new_with_mnemonic (_("Presidentielle"));
  gtk_widget_show (YZ_checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_checkbutton1, 240, 512);
  gtk_widget_set_size_request (YZ_checkbutton1, 118, 24);

  YZ_checkbutton2 = gtk_check_button_new_with_mnemonic (_("Handicap"));
  gtk_widget_show (YZ_checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_checkbutton2, 240, 536);
  gtk_widget_set_size_request (YZ_checkbutton2, 118, 24);

  image16 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed5), image16, 56, 96);
  gtk_widget_set_size_request (image16, 21, 21);

  YZ_label18 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label18);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label18, 48, 96);
  gtk_widget_set_size_request (YZ_label18, 141, 17);

  image22 = gtk_image_new_from_icon_name ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed5), image22, 400, 32);
  gtk_widget_set_size_request (image22, 136, 72);

  YZ_label23 = gtk_label_new (_("<span foreground=\"green\" weight=\"bold\" size=\"medium\">Param\303\250tres</span>"));
  gtk_widget_show (YZ_label23);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label23, 416, 32);
  gtk_widget_set_size_request (YZ_label23, 145, 40);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label23), TRUE);

  YZ_label21 = gtk_label_new (_("Numero de matricule"));
  gtk_widget_show (YZ_label21);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label21, 24, 288);
  gtk_widget_set_size_request (YZ_label21, 152, 40);

  image77 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image77);
  gtk_fixed_put (GTK_FIXED (fixed5), image77, -8, 0);
  gtk_widget_set_size_request (image77, 32, 592);

  image20 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed5), image20, 560, 32);
  gtk_widget_set_size_request (image20, 56, 560);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed5), button6, 432, 496);
  gtk_widget_set_size_request (button6, 96, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button6), alignment21);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox17);

  image58 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox17), image58, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("<span foreground=\"gray\" weight=\"bold\" size=\"12000\">Modifier</span>"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox17), label54, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  image21 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed5), image21, 24, 0);
  gtk_widget_set_size_request (image21, 616, 32);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed5), button14, 480, 88);
  gtk_widget_set_size_request (button14, 72, 40);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button14), alignment29);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox25);

  image66 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox25), image66, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox25), label68, FALSE, FALSE, 0);

  YZ_label8 = gtk_label_new (_("<span foreground=\"royalblue\" weight=\"bold\" size=\"12000\">Modifier</span>"));
  gtk_widget_show (YZ_label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), YZ_label8);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label8), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entry_id_service3 = gtk_entry_new ();
  gtk_widget_show (entry_id_service3);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_id_service3, 184, 104);
  gtk_widget_set_size_request (entry_id_service3, 256, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service3), 8226);

  image30 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed8), image30, 88, 112);
  gtk_widget_set_size_request (image30, 21, 21);

  image33 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed8), image33, 552, 64);
  gtk_widget_set_size_request (image33, 80, 232);

  YZ_label35 = gtk_label_new (_("<span foreground=\"green\" weight=\"bold\" size=\"medium\">Supprimer</span>"));
  gtk_widget_show (YZ_label35);
  gtk_fixed_put (GTK_FIXED (fixed8), YZ_label35, 456, 72);
  gtk_widget_set_size_request (YZ_label35, 92, 17);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label35), TRUE);

  image32 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed8), image32, -8, 0);
  gtk_widget_set_size_request (image32, 640, 64);

  YZ_label32 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label32);
  gtk_fixed_put (GTK_FIXED (fixed8), YZ_label32, 72, 112);
  gtk_widget_set_size_request (YZ_label32, 141, 17);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed8), button15, 456, 104);
  gtk_widget_set_size_request (button15, 80, 40);

  image71 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image71);
  gtk_container_add (GTK_CONTAINER (button15), image71);

  image31 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed8), image31, -8, 160);
  gtk_widget_set_size_request (image31, 728, 896);

  image34 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed8), image34, -8, 64);
  gtk_widget_set_size_request (image34, 88, 96);

  YZ_label9 = gtk_label_new_with_mnemonic (_("<span foreground=\"royalblue\" weight=\"bold\" size=\"12000\">Supprimer</span>"));
  gtk_widget_show (YZ_label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), YZ_label9);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label9), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entry_id_service1 = gtk_entry_new ();
  gtk_widget_show (entry_id_service1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_id_service1, 168, 88);
  gtk_widget_set_size_request (entry_id_service1, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service1), 8226);

  image23 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed7), image23, 48, 104);
  gtk_widget_set_size_request (image23, 35, 21);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox1, 216, 152);
  gtk_widget_set_size_request (eventbox1, 227, 36);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_container_add (GTK_CONTAINER (eventbox1), combobox3);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Voiture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Velo "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Moto"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("scooters"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Autobus"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("caravanes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Bicycles_et_scooter_\303\251lectriques"));

  entry_matricule1 = gtk_entry_new ();
  gtk_widget_show (entry_matricule1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_matricule1, 176, 272);
  gtk_widget_set_size_request (entry_matricule1, 304, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_matricule1), 8226);

  YZ_label26 = gtk_label_new (_("Types de transport"));
  gtk_widget_show (YZ_label26);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label26, 40, 160);
  gtk_widget_set_size_request (YZ_label26, 205, 17);

  YZ_label27 = gtk_label_new (_("Numero de place "));
  gtk_widget_show (YZ_label27);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label27, 120, 224);
  gtk_widget_set_size_request (YZ_label27, 184, 17);

  YZ_label28 = gtk_label_new (_("Numero de matricule"));
  gtk_widget_show (YZ_label28);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label28, 0, 288);
  gtk_widget_set_size_request (YZ_label28, 198, 17);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox2, 216, 336);
  gtk_widget_set_size_request (eventbox2, 232, 40);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_container_add (GTK_CONTAINER (eventbox2), combobox4);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Borne_de_chage_\303\251l\303\251ctrique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Lavage "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Maintenance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("S\303\251curit\303\251_et_surveillance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Services_de_valet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Espace_covoiturage"));

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment9);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment9, 280, 216);
  gtk_widget_set_size_request (alignment9, 96, 32);

  spinButton_place2_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinButton_place2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinButton_place2_adj), 1, 0);
  gtk_widget_show (spinButton_place2);
  gtk_container_add (GTK_CONTAINER (alignment9), spinButton_place2);
  gtk_widget_set_size_request (spinButton_place2, 96, 32);

  YZ_label25 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label25);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label25, 48, 104);
  gtk_widget_set_size_request (YZ_label25, 141, 17);

  YZ_label29 = gtk_label_new (_("Type de service"));
  gtk_widget_show (YZ_label29);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label29, 72, 352);
  gtk_widget_set_size_request (YZ_label29, 159, 17);

  image28 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed7), image28, 592, 0);
  gtk_widget_set_size_request (image28, 32, 664);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed7), button17, 416, 536);
  gtk_widget_set_size_request (button17, 120, 32);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (button17), alignment32);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox28);

  image74 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image74);
  gtk_box_pack_start (GTK_BOX (hbox28), image74, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("<span foreground=\"gray\" weight=\"bold\" size=\"12000\">Retour</span>\n"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox28), label71, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label71), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 416, 504);
  gtk_widget_set_size_request (button8, 120, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button8), alignment23);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox19);

  image60 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox19), image60, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("<span foreground=\"gray\" weight=\"bold\" size=\"12000\">Enregistrer</span>\n"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox19), label56, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  image25 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed7), image25, 400, 64);
  gtk_widget_set_size_request (image25, 21, 21);

  YZ_label31 = gtk_label_new (_("<span foreground=\"green\" weight=\"bold\" size=\"medium\">Page d'accueil</span>\n\n"));
  gtk_widget_show (YZ_label31);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label31, 416, 64);
  gtk_widget_set_size_request (YZ_label31, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label31), TRUE);

  image29 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed7), image29, 24, 0);
  gtk_widget_set_size_request (image29, 568, 56);

  image76 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image76);
  gtk_fixed_put (GTK_FIXED (fixed7), image76, 552, 56);
  gtk_widget_set_size_request (image76, 48, 520);

  image27 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed7), image27, 24, 576);
  gtk_widget_set_size_request (image27, 576, 128);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Presidentielle"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbutton3, 248, 472);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Premium"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton3, 200, 416);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), YZ_radiobutton2_group);
  YZ_radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Normal"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton4, 344, 416);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), YZ_radiobutton2_group);
  YZ_radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Handicap"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbutton4, 248, 496);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  image26 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed7), image26, -16, 0);
  gtk_widget_set_size_request (image26, 40, 688);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed7), button18, 48, 520);
  gtk_widget_set_size_request (button18, 96, 40);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (button18), alignment33);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox29);

  image79 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image79);
  gtk_box_pack_start (GTK_BOX (hbox29), image79, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("<span foreground=\"gray\" weight=\"bold\" size=\"12000\">Cancel</span>"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox29), label72, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label72), TRUE);

  fenetre_ajout = gtk_label_new (_("<span foreground=\"royalblue\" weight=\"bold\" size=\"12000\">Ajouter</span>"));
  gtk_widget_show (fenetre_ajout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), fenetre_ajout);
  gtk_label_set_use_markup (GTK_LABEL (fenetre_ajout), TRUE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  YZ_entry11 = gtk_entry_new ();
  gtk_widget_show (YZ_entry11);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_entry11, 176, 80);
  gtk_widget_set_size_request (YZ_entry11, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (YZ_entry11), 8226);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_fixed_put (GTK_FIXED (fixed9), eventbox3, 224, 128);
  gtk_widget_set_size_request (eventbox3, 214, 41);

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_container_add (GTK_CONTAINER (eventbox3), combobox5);
  gtk_widget_set_size_request (combobox5, 214, 41);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Borne de charge pour voiture \303\251lectrique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Lavage "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Maintenance"));

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed9), button10, 408, 192);
  gtk_widget_set_size_request (button10, 128, 32);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button10), alignment25);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox21);

  image62 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox21), image62, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("<span foreground=\"gray\" weight=\"bold\" size=\"12000\">R\303\251server</span>"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox21), label58, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  YZ_label37 = gtk_label_new (_("Type de service"));
  gtk_widget_show (YZ_label37);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_label37, 72, 136);
  gtk_widget_set_size_request (YZ_label37, 159, 17);

  image44 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image44);
  gtk_fixed_put (GTK_FIXED (fixed9), image44, -8, 240);
  gtk_widget_set_size_request (image44, 600, 464);

  YZ_label39 = gtk_label_new (_("<span foreground=\"black\" weight=\"bold\" size=\"15000\">R\303\251servation acc\303\250s rapide</span>\n"));
  gtk_widget_show (YZ_label39);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_label39, 272, 48);
  gtk_widget_set_size_request (YZ_label39, 272, 24);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label39), TRUE);

  image45 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image45);
  gtk_fixed_put (GTK_FIXED (fixed9), image45, 544, 0);
  gtk_widget_set_size_request (image45, 45, 240);

  image39 = gtk_image_new_from_icon_name ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed9), image39, 264, 48);
  gtk_widget_set_size_request (image39, 21, 21);

  image47 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image47);
  gtk_fixed_put (GTK_FIXED (fixed9), image47, 64, 0);
  gtk_widget_set_size_request (image47, 480, 40);

  image46 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image46);
  gtk_fixed_put (GTK_FIXED (fixed9), image46, -8, 0);
  gtk_widget_set_size_request (image46, 72, 240);

  image36 = gtk_image_new_from_icon_name ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed9), image36, 72, 88);
  gtk_widget_set_size_request (image36, 21, 21);

  YZ_label36 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label36);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_label36, 64, 88);
  gtk_widget_set_size_request (YZ_label36, 141, 17);

  YZ_label11 = gtk_label_new (_("<span foreground=\"royalblue\" weight=\"bold\" size=\"12000\">R\303\251servation de service</span>"));
  gtk_widget_show (YZ_label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), YZ_label11);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label11), TRUE);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  YZ_entry12 = gtk_entry_new ();
  gtk_widget_show (YZ_entry12);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_entry12, 168, 104);
  gtk_widget_set_size_request (YZ_entry12, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (YZ_entry12), 8226);

  YZ_entry13 = gtk_entry_new ();
  gtk_widget_show (YZ_entry13);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_entry13, 168, 160);
  gtk_widget_set_size_request (YZ_entry13, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (YZ_entry13), 8226);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed10), button12, 328, 224);
  gtk_widget_set_size_request (button12, 123, 29);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button12), alignment27);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox23);

  image64 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox23), image64, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("<span foreground=\"gray\" weight=\"bold\" size=\"12000\">Rafra\303\256chir</span>"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox23), label60, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed10), button11, 184, 224);
  gtk_widget_set_size_request (button11, 125, 29);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button11), alignment26);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox22);

  image63 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_box_pack_start (GTK_BOX (hbox22), image63, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("<span foreground=\"gray\" weight=\"bold\" size=\"12000\">Enregistrer</span>"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox22), label59, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  image50 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image50);
  gtk_fixed_put (GTK_FIXED (fixed10), image50, -8, 0);
  gtk_widget_set_size_request (image50, 64, 280);

  image51 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image51);
  gtk_fixed_put (GTK_FIXED (fixed10), image51, 56, 0);
  gtk_widget_set_size_request (image51, 472, 56);

  image43 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_fixed_put (GTK_FIXED (fixed10), image43, 392, 72);
  gtk_widget_set_size_request (image43, 21, 21);

  YZ_label45 = gtk_label_new (_("<span foreground=\"black\" weight=\"bold\" size=\"14000\">Affectation  </span>"));
  gtk_widget_show (YZ_label45);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_label45, 416, 72);
  gtk_widget_set_size_request (YZ_label45, 121, 17);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label45), TRUE);

  image49 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image49);
  gtk_fixed_put (GTK_FIXED (fixed10), image49, 528, 0);
  gtk_widget_set_size_request (image49, 64, 280);

  image48 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image48);
  gtk_fixed_put (GTK_FIXED (fixed10), image48, -8, 280);
  gtk_widget_set_size_request (image48, 600, 424);

  lYZ_abel44 = gtk_label_new (_("ID r\303\251servation"));
  gtk_widget_show (lYZ_abel44);
  gtk_fixed_put (GTK_FIXED (fixed10), lYZ_abel44, 48, 168);
  gtk_widget_set_size_request (lYZ_abel44, 141, 17);

  image40 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed10), image40, 64, 120);
  gtk_widget_set_size_request (image40, 35, 21);

  YZ_label42 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label42);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_label42, 80, 120);
  gtk_widget_set_size_request (YZ_label42, 101, 16);

  YZ_label12 = gtk_label_new (_("<span foreground=\"royalblue\" weight=\"bold\" size=\"12000\">Affectation</span>"));
  gtk_widget_show (YZ_label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), YZ_label12);
  gtk_label_set_use_markup (GTK_LABEL (YZ_label12), TRUE);

  g_signal_connect ((gpointer) treeview_service, "row_activated",
                    G_CALLBACK (on_treeview_service_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) YZ_radiobutton2, "toggled",
                    G_CALLBACK (on_YZ_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) YZ_radiobutton1, "toggled",
                    G_CALLBACK (on_YZ_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) YZ_checkbutton1, "toggled",
                    G_CALLBACK (on_YZ_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) YZ_checkbutton2, "toggled",
                    G_CALLBACK (on_YZ_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, treeview_service, "treeview_service");
  GLADE_HOOKUP_OBJECT (window3, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window3, image8, "image8");
  GLADE_HOOKUP_OBJECT (window3, Yz_ID_service, "Yz_ID_service");
  GLADE_HOOKUP_OBJECT (window3, button16, "button16");
  GLADE_HOOKUP_OBJECT (window3, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window3, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window3, image73, "image73");
  GLADE_HOOKUP_OBJECT (window3, label70, "label70");
  GLADE_HOOKUP_OBJECT (window3, image15, "image15");
  GLADE_HOOKUP_OBJECT (window3, image12, "image12");
  GLADE_HOOKUP_OBJECT (window3, image13, "image13");
  GLADE_HOOKUP_OBJECT (window3, button3, "button3");
  GLADE_HOOKUP_OBJECT (window3, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window3, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window3, image72, "image72");
  GLADE_HOOKUP_OBJECT (window3, label69, "label69");
  GLADE_HOOKUP_OBJECT (window3, button4, "button4");
  GLADE_HOOKUP_OBJECT (window3, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window3, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window3, image56, "image56");
  GLADE_HOOKUP_OBJECT (window3, label52, "label52");
  GLADE_HOOKUP_OBJECT (window3, button2, "button2");
  GLADE_HOOKUP_OBJECT (window3, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window3, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window3, image54, "image54");
  GLADE_HOOKUP_OBJECT (window3, label50, "label50");
  GLADE_HOOKUP_OBJECT (window3, button5, "button5");
  GLADE_HOOKUP_OBJECT (window3, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window3, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window3, image57, "image57");
  GLADE_HOOKUP_OBJECT (window3, label53, "label53");
  GLADE_HOOKUP_OBJECT (window3, image78, "image78");
  GLADE_HOOKUP_OBJECT (window3, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (window3, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window3, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window3, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window3, spinButton_place, "spinButton_place");
  GLADE_HOOKUP_OBJECT (window3, entry_id_service, "entry_id_service");
  GLADE_HOOKUP_OBJECT (window3, entry_matricule, "entry_matricule");
  GLADE_HOOKUP_OBJECT (window3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window3, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (window3, YZ_label19, "YZ_label19");
  GLADE_HOOKUP_OBJECT (window3, YZ_label20, "YZ_label20");
  GLADE_HOOKUP_OBJECT (window3, YZ_label22, "YZ_label22");
  GLADE_HOOKUP_OBJECT (window3, YZ_radiobutton2, "YZ_radiobutton2");
  GLADE_HOOKUP_OBJECT (window3, YZ_radiobutton1, "YZ_radiobutton1");
  GLADE_HOOKUP_OBJECT (window3, image19, "image19");
  GLADE_HOOKUP_OBJECT (window3, image75, "image75");
  GLADE_HOOKUP_OBJECT (window3, YZ_checkbutton1, "YZ_checkbutton1");
  GLADE_HOOKUP_OBJECT (window3, YZ_checkbutton2, "YZ_checkbutton2");
  GLADE_HOOKUP_OBJECT (window3, image16, "image16");
  GLADE_HOOKUP_OBJECT (window3, YZ_label18, "YZ_label18");
  GLADE_HOOKUP_OBJECT (window3, image22, "image22");
  GLADE_HOOKUP_OBJECT (window3, YZ_label23, "YZ_label23");
  GLADE_HOOKUP_OBJECT (window3, YZ_label21, "YZ_label21");
  GLADE_HOOKUP_OBJECT (window3, image77, "image77");
  GLADE_HOOKUP_OBJECT (window3, image20, "image20");
  GLADE_HOOKUP_OBJECT (window3, button6, "button6");
  GLADE_HOOKUP_OBJECT (window3, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window3, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window3, image58, "image58");
  GLADE_HOOKUP_OBJECT (window3, label54, "label54");
  GLADE_HOOKUP_OBJECT (window3, image21, "image21");
  GLADE_HOOKUP_OBJECT (window3, button14, "button14");
  GLADE_HOOKUP_OBJECT (window3, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window3, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window3, image66, "image66");
  GLADE_HOOKUP_OBJECT (window3, label68, "label68");
  GLADE_HOOKUP_OBJECT (window3, YZ_label8, "YZ_label8");
  GLADE_HOOKUP_OBJECT (window3, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window3, entry_id_service3, "entry_id_service3");
  GLADE_HOOKUP_OBJECT (window3, image30, "image30");
  GLADE_HOOKUP_OBJECT (window3, image33, "image33");
  GLADE_HOOKUP_OBJECT (window3, YZ_label35, "YZ_label35");
  GLADE_HOOKUP_OBJECT (window3, image32, "image32");
  GLADE_HOOKUP_OBJECT (window3, YZ_label32, "YZ_label32");
  GLADE_HOOKUP_OBJECT (window3, button15, "button15");
  GLADE_HOOKUP_OBJECT (window3, image71, "image71");
  GLADE_HOOKUP_OBJECT (window3, image31, "image31");
  GLADE_HOOKUP_OBJECT (window3, image34, "image34");
  GLADE_HOOKUP_OBJECT (window3, YZ_label9, "YZ_label9");
  GLADE_HOOKUP_OBJECT (window3, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window3, entry_id_service1, "entry_id_service1");
  GLADE_HOOKUP_OBJECT (window3, image23, "image23");
  GLADE_HOOKUP_OBJECT (window3, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window3, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (window3, entry_matricule1, "entry_matricule1");
  GLADE_HOOKUP_OBJECT (window3, YZ_label26, "YZ_label26");
  GLADE_HOOKUP_OBJECT (window3, YZ_label27, "YZ_label27");
  GLADE_HOOKUP_OBJECT (window3, YZ_label28, "YZ_label28");
  GLADE_HOOKUP_OBJECT (window3, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (window3, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (window3, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window3, spinButton_place2, "spinButton_place2");
  GLADE_HOOKUP_OBJECT (window3, YZ_label25, "YZ_label25");
  GLADE_HOOKUP_OBJECT (window3, YZ_label29, "YZ_label29");
  GLADE_HOOKUP_OBJECT (window3, image28, "image28");
  GLADE_HOOKUP_OBJECT (window3, button17, "button17");
  GLADE_HOOKUP_OBJECT (window3, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window3, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window3, image74, "image74");
  GLADE_HOOKUP_OBJECT (window3, label71, "label71");
  GLADE_HOOKUP_OBJECT (window3, button8, "button8");
  GLADE_HOOKUP_OBJECT (window3, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window3, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window3, image60, "image60");
  GLADE_HOOKUP_OBJECT (window3, label56, "label56");
  GLADE_HOOKUP_OBJECT (window3, image25, "image25");
  GLADE_HOOKUP_OBJECT (window3, YZ_label31, "YZ_label31");
  GLADE_HOOKUP_OBJECT (window3, image29, "image29");
  GLADE_HOOKUP_OBJECT (window3, image76, "image76");
  GLADE_HOOKUP_OBJECT (window3, image27, "image27");
  GLADE_HOOKUP_OBJECT (window3, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window3, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window3, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window3, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window3, image26, "image26");
  GLADE_HOOKUP_OBJECT (window3, button18, "button18");
  GLADE_HOOKUP_OBJECT (window3, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (window3, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window3, image79, "image79");
  GLADE_HOOKUP_OBJECT (window3, label72, "label72");
  GLADE_HOOKUP_OBJECT (window3, fenetre_ajout, "fenetre_ajout");
  GLADE_HOOKUP_OBJECT (window3, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window3, YZ_entry11, "YZ_entry11");
  GLADE_HOOKUP_OBJECT (window3, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (window3, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (window3, button10, "button10");
  GLADE_HOOKUP_OBJECT (window3, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window3, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window3, image62, "image62");
  GLADE_HOOKUP_OBJECT (window3, label58, "label58");
  GLADE_HOOKUP_OBJECT (window3, YZ_label37, "YZ_label37");
  GLADE_HOOKUP_OBJECT (window3, image44, "image44");
  GLADE_HOOKUP_OBJECT (window3, YZ_label39, "YZ_label39");
  GLADE_HOOKUP_OBJECT (window3, image45, "image45");
  GLADE_HOOKUP_OBJECT (window3, image39, "image39");
  GLADE_HOOKUP_OBJECT (window3, image47, "image47");
  GLADE_HOOKUP_OBJECT (window3, image46, "image46");
  GLADE_HOOKUP_OBJECT (window3, image36, "image36");
  GLADE_HOOKUP_OBJECT (window3, YZ_label36, "YZ_label36");
  GLADE_HOOKUP_OBJECT (window3, YZ_label11, "YZ_label11");
  GLADE_HOOKUP_OBJECT (window3, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window3, YZ_entry12, "YZ_entry12");
  GLADE_HOOKUP_OBJECT (window3, YZ_entry13, "YZ_entry13");
  GLADE_HOOKUP_OBJECT (window3, button12, "button12");
  GLADE_HOOKUP_OBJECT (window3, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window3, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window3, image64, "image64");
  GLADE_HOOKUP_OBJECT (window3, label60, "label60");
  GLADE_HOOKUP_OBJECT (window3, button11, "button11");
  GLADE_HOOKUP_OBJECT (window3, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window3, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window3, image63, "image63");
  GLADE_HOOKUP_OBJECT (window3, label59, "label59");
  GLADE_HOOKUP_OBJECT (window3, image50, "image50");
  GLADE_HOOKUP_OBJECT (window3, image51, "image51");
  GLADE_HOOKUP_OBJECT (window3, image43, "image43");
  GLADE_HOOKUP_OBJECT (window3, YZ_label45, "YZ_label45");
  GLADE_HOOKUP_OBJECT (window3, image49, "image49");
  GLADE_HOOKUP_OBJECT (window3, image48, "image48");
  GLADE_HOOKUP_OBJECT (window3, lYZ_abel44, "lYZ_abel44");
  GLADE_HOOKUP_OBJECT (window3, image40, "image40");
  GLADE_HOOKUP_OBJECT (window3, YZ_label42, "YZ_label42");
  GLADE_HOOKUP_OBJECT (window3, YZ_label12, "YZ_label12");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed11;
  GtkWidget *entry_Nom;
  GtkWidget *entry_Prenom;
  GtkWidget *entry_Username;
  GtkWidget *entry_Password;
  GtkWidget *image68;
  GtkWidget *image67;
  GtkWidget *image70;
  GtkWidget *image69;
  GtkWidget *button13;
  GtkWidget *alignment28;
  GtkWidget *hbox24;
  GtkWidget *image65;
  GtkWidget *label67;
  GtkWidget *label64;
  GtkWidget *label63;
  GtkWidget *label62;
  GtkWidget *label61;
  GtkWidget *label66;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window4), fixed11);

  entry_Nom = gtk_entry_new ();
  gtk_widget_show (entry_Nom);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Nom, 120, 88);
  gtk_widget_set_size_request (entry_Nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Nom), 8226);

  entry_Prenom = gtk_entry_new ();
  gtk_widget_show (entry_Prenom);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Prenom, 120, 120);
  gtk_widget_set_size_request (entry_Prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Prenom), 8226);

  entry_Username = gtk_entry_new ();
  gtk_widget_show (entry_Username);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Username, 120, 152);
  gtk_widget_set_size_request (entry_Username, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Username), 8226);

  entry_Password = gtk_entry_new ();
  gtk_widget_show (entry_Password);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Password, 120, 184);
  gtk_widget_set_size_request (entry_Password, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Password), 8226);

  image68 = create_pixmap (window4, "Screenshot from 2024-11-13 01-18-35.png");
  gtk_widget_show (image68);
  gtk_fixed_put (GTK_FIXED (fixed11), image68, 0, 0);
  gtk_widget_set_size_request (image68, 40, 352);

  image67 = create_pixmap (window4, "Screenshot from 2024-11-13 01-18-35.png");
  gtk_widget_show (image67);
  gtk_fixed_put (GTK_FIXED (fixed11), image67, 344, -8);
  gtk_widget_set_size_request (image67, 48, 360);

  image70 = create_pixmap (window4, "Screenshot from 2024-11-13 01-18-35.png");
  gtk_widget_show (image70);
  gtk_fixed_put (GTK_FIXED (fixed11), image70, 40, 0);
  gtk_widget_set_size_request (image70, 304, 56);

  image69 = create_pixmap (window4, "Screenshot from 2024-11-13 01-18-35.png");
  gtk_widget_show (image69);
  gtk_fixed_put (GTK_FIXED (fixed11), image69, 40, 272);
  gtk_widget_set_size_request (image69, 304, 80);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed11), button13, 160, 216);
  gtk_widget_set_size_request (button13, 90, 32);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button13), alignment28);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox24);

  image65 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox24), image65, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\">Ajouter</span>"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox24), label67, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  label64 = gtk_label_new (_("Password"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed11), label64, 40, 192);
  gtk_widget_set_size_request (label64, 87, 17);

  label63 = gtk_label_new (_("Username"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed11), label63, 24, 160);
  gtk_widget_set_size_request (label63, 112, 16);

  label62 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed11), label62, 56, 128);
  gtk_widget_set_size_request (label62, 63, 17);

  label61 = gtk_label_new (_("Nom"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed11), label61, 64, 96);
  gtk_widget_set_size_request (label61, 49, 17);

  label66 = gtk_label_new (_("<span foreground=\"black\">inscription</span>"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed11), label66, 144, 64);
  gtk_widget_set_size_request (label66, 111, 17);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window4, entry_Nom, "entry_Nom");
  GLADE_HOOKUP_OBJECT (window4, entry_Prenom, "entry_Prenom");
  GLADE_HOOKUP_OBJECT (window4, entry_Username, "entry_Username");
  GLADE_HOOKUP_OBJECT (window4, entry_Password, "entry_Password");
  GLADE_HOOKUP_OBJECT (window4, image68, "image68");
  GLADE_HOOKUP_OBJECT (window4, image67, "image67");
  GLADE_HOOKUP_OBJECT (window4, image70, "image70");
  GLADE_HOOKUP_OBJECT (window4, image69, "image69");
  GLADE_HOOKUP_OBJECT (window4, button13, "button13");
  GLADE_HOOKUP_OBJECT (window4, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window4, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window4, image65, "image65");
  GLADE_HOOKUP_OBJECT (window4, label67, "label67");
  GLADE_HOOKUP_OBJECT (window4, label64, "label64");
  GLADE_HOOKUP_OBJECT (window4, label63, "label63");
  GLADE_HOOKUP_OBJECT (window4, label62, "label62");
  GLADE_HOOKUP_OBJECT (window4, label61, "label61");
  GLADE_HOOKUP_OBJECT (window4, label66, "label66");

  return window4;
}

