/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry_Username;
  GtkWidget *entry_Password;
  GtkWidget *image2;
  GtkWidget *YZ_Login;
  GtkWidget *YZ_Mot_de_passe;
  GtkWidget *image1;
  GtkWidget *YZ_Authentication;
  GtkWidget *button1;
  GtkWidget *alignment16;
  GtkWidget *hbox12;
  GtkWidget *image53;
  GtkWidget *label49;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry_Username = gtk_entry_new ();
  gtk_widget_show (entry_Username);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_Username, 136, 104);
  gtk_widget_set_size_request (entry_Username, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Username), 8226);

  entry_Password = gtk_entry_new ();
  gtk_widget_show (entry_Password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_Password, 136, 144);
  gtk_widget_set_size_request (entry_Password, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Password), 8226);

  image2 = create_pixmap (window1, "Firefox_wallpaper.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1), image2, 0, 0);
  gtk_widget_set_size_request (image2, 432, 72);

  YZ_Login = gtk_label_new (_("Login"));
  gtk_widget_show (YZ_Login);
  gtk_fixed_put (GTK_FIXED (fixed1), YZ_Login, 64, 112);
  gtk_widget_set_size_request (YZ_Login, 64, 16);

  YZ_Mot_de_passe = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (YZ_Mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed1), YZ_Mot_de_passe, 16, 152);
  gtk_widget_set_size_request (YZ_Mot_de_passe, 136, 16);

  image1 = create_pixmap (window1, "Firefox_wallpaper.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 232);
  gtk_widget_set_size_request (image1, 432, 88);

  YZ_Authentication = gtk_label_new (_("Authentification"));
  gtk_widget_show (YZ_Authentication);
  gtk_fixed_put (GTK_FIXED (fixed1), YZ_Authentication, 152, 80);
  gtk_widget_set_size_request (YZ_Authentication, 128, 16);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 152, 184);
  gtk_widget_set_size_request (button1, 120, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button1), alignment16);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox12);

  image53 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox12), image53, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox12), label49, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry_Username, "entry_Username");
  GLADE_HOOKUP_OBJECT (window1, entry_Password, "entry_Password");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, YZ_Login, "YZ_Login");
  GLADE_HOOKUP_OBJECT (window1, YZ_Mot_de_passe, "YZ_Mot_de_passe");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, YZ_Authentication, "YZ_Authentication");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image53, "image53");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");

  return window1;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *treeview1;
  GtkWidget *entry3;
  GtkWidget *image8;
  GtkWidget *image12;
  GtkWidget *image15;
  GtkWidget *image13;
  GtkWidget *image14;
  GtkWidget *Yz_ID_service;
  GtkWidget *button2;
  GtkWidget *alignment17;
  GtkWidget *hbox13;
  GtkWidget *image54;
  GtkWidget *label50;
  GtkWidget *button3;
  GtkWidget *alignment18;
  GtkWidget *hbox14;
  GtkWidget *image55;
  GtkWidget *label51;
  GtkWidget *button4;
  GtkWidget *alignment19;
  GtkWidget *hbox15;
  GtkWidget *image56;
  GtkWidget *label52;
  GtkWidget *button5;
  GtkWidget *alignment20;
  GtkWidget *hbox16;
  GtkWidget *image57;
  GtkWidget *label53;
  GtkWidget *YZ_label7;
  GtkWidget *fixed5;
  GtkWidget *alignment5;
  GtkWidget *combobox1;
  GtkObject *spinButton_place_adj;
  GtkWidget *spinButton_place;
  GtkWidget *entry_id_service;
  GtkWidget *entry_matricule;
  GtkWidget *alignment6;
  GtkWidget *combobox2;
  GtkWidget *image17;
  GtkWidget *image21;
  GtkWidget *YZ_label19;
  GtkWidget *YZ_label20;
  GtkWidget *YZ_label21;
  GtkWidget *YZ_label22;
  GtkWidget *image19;
  GtkWidget *image20;
  GtkWidget *button6;
  GtkWidget *alignment21;
  GtkWidget *hbox17;
  GtkWidget *image58;
  GtkWidget *label54;
  GtkWidget *image16;
  GtkWidget *YZ_label18;
  GtkWidget *YZ_label23;
  GtkWidget *image22;
  GtkWidget *button14;
  GtkWidget *alignment29;
  GtkWidget *hbox25;
  GtkWidget *image66;
  GtkWidget *label68;
  GtkWidget *YZ_radiobutton1;
  GSList *YZ_radiobutton1_group = NULL;
  GtkWidget *YZ_checkbutton2;
  GtkWidget *YZ_checkbutton1;
  GtkWidget *YZ_radiobutton2;
  GtkWidget *YZ_label8;
  GtkWidget *fixed8;
  GtkWidget *entry_id_service3;
  GtkWidget *image32;
  GtkWidget *image30;
  GtkWidget *YZ_label35;
  GtkWidget *YZ_label32;
  GtkWidget *image33;
  GtkWidget *image31;
  GtkWidget *image34;
  GtkWidget *button7;
  GtkWidget *alignment22;
  GtkWidget *hbox18;
  GtkWidget *image59;
  GtkWidget *label55;
  GtkWidget *YZ_label9;
  GtkWidget *fixed7;
  GtkWidget *entry_id_service1;
  GtkWidget *image23;
  GtkWidget *eventbox1;
  GtkWidget *combobox3;
  GtkWidget *entry_matricule1;
  GtkWidget *YZ_label26;
  GtkWidget *YZ_label27;
  GtkWidget *YZ_label28;
  GtkWidget *image26;
  GtkWidget *image27;
  GtkWidget *image28;
  GtkWidget *image25;
  GtkWidget *YZ_label31;
  GtkWidget *eventbox2;
  GtkWidget *combobox4;
  GtkWidget *alignment9;
  GtkObject *spinButton_place2_adj;
  GtkWidget *spinButton_place2;
  GtkWidget *YZ_label25;
  GtkWidget *YZ_label29;
  GtkWidget *image29;
  GtkWidget *button8;
  GtkWidget *alignment23;
  GtkWidget *hbox19;
  GtkWidget *image60;
  GtkWidget *label56;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton3;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *YZ_label10;
  GtkWidget *fixed9;
  GtkWidget *YZ_entry11;
  GtkWidget *comboboxentry5;
  GtkWidget *YZ_label37;
  GtkWidget *YZ_label36;
  GtkWidget *image36;
  GtkWidget *image39;
  GtkWidget *YZ_label39;
  GtkWidget *image47;
  GtkWidget *image44;
  GtkWidget *image45;
  GtkWidget *image46;
  GtkWidget *button10;
  GtkWidget *alignment25;
  GtkWidget *hbox21;
  GtkWidget *image62;
  GtkWidget *label58;
  GtkWidget *button9;
  GtkWidget *alignment24;
  GtkWidget *hbox20;
  GtkWidget *image61;
  GtkWidget *label57;
  GtkWidget *YZ_label11;
  GtkWidget *fixed10;
  GtkWidget *YZ_entry12;
  GtkWidget *YZ_entry13;
  GtkWidget *image40;
  GtkWidget *YZ_label42;
  GtkWidget *lYZ_abel44;
  GtkWidget *image43;
  GtkWidget *image48;
  GtkWidget *YZ_label45;
  GtkWidget *image50;
  GtkWidget *image49;
  GtkWidget *image51;
  GtkWidget *button12;
  GtkWidget *alignment27;
  GtkWidget *hbox23;
  GtkWidget *image64;
  GtkWidget *label60;
  GtkWidget *button11;
  GtkWidget *alignment26;
  GtkWidget *hbox22;
  GtkWidget *image63;
  GtkWidget *label59;
  GtkWidget *YZ_label12;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 624, 688);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 112, 128);
  gtk_widget_set_size_request (treeview1, 416, 320);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 208, 72);
  gtk_widget_set_size_request (entry3, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  image8 = gtk_image_new_from_icon_name ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed4), image8, 120, 80);
  gtk_widget_set_size_request (image8, 21, 21);

  image12 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed4), image12, -24, 0);
  gtk_widget_set_size_request (image12, 136, 520);

  image15 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed4), image15, 112, 0);
  gtk_widget_set_size_request (image15, 416, 64);

  image13 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed4), image13, 528, 0);
  gtk_widget_set_size_request (image13, 120, 520);

  image14 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed4), image14, -8, 520);
  gtk_widget_set_size_request (image14, 632, 144);

  Yz_ID_service = gtk_label_new (_("ID service"));
  gtk_widget_show (Yz_ID_service);
  gtk_fixed_put (GTK_FIXED (fixed4), Yz_ID_service, 104, 80);
  gtk_widget_set_size_request (Yz_ID_service, 141, 17);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 416, 72);
  gtk_widget_set_size_request (button2, 106, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button2), alignment17);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox13);

  image54 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox13), image54, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox13), label50, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 152, 472);
  gtk_widget_set_size_request (button3, 98, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button3), alignment18);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox14);

  image55 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox14), image55, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox14), label51, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 264, 472);
  gtk_widget_set_size_request (button4, 106, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button4), alignment19);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox15);

  image56 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox15), image56, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox15), label52, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 392, 472);
  gtk_widget_set_size_request (button5, 102, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button5), alignment20);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox16);

  image57 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox16), image57, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("R\303\251frecher"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox16), label53, FALSE, FALSE, 0);

  YZ_label7 = gtk_label_new (_("Afficher"));
  gtk_widget_show (YZ_label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), YZ_label7);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment5, 208, 160);
  gtk_widget_set_size_request (alignment5, 234, 41);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_container_add (GTK_CONTAINER (alignment5), combobox1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Voiture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Velo "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Moto"));

  spinButton_place_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinButton_place = gtk_spin_button_new (GTK_ADJUSTMENT (spinButton_place_adj), 1, 0);
  gtk_widget_show (spinButton_place);
  gtk_fixed_put (GTK_FIXED (fixed5), spinButton_place, 280, 232);
  gtk_widget_set_size_request (spinButton_place, 96, 32);

  entry_id_service = gtk_entry_new ();
  gtk_widget_show (entry_id_service);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_id_service, 168, 88);
  gtk_widget_set_size_request (entry_id_service, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service), 8226);

  entry_matricule = gtk_entry_new ();
  gtk_widget_show (entry_matricule);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_matricule, 176, 288);
  gtk_widget_set_size_request (entry_matricule, 304, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_matricule), 8226);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment6);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment6, 216, 360);
  gtk_widget_set_size_request (alignment6, 235, 43);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_container_add (GTK_CONTAINER (alignment6), combobox2);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Borne de charge pour voiture \303\251lectrique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Lavage "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Maintenance"));

  image17 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed5), image17, 600, 0);
  gtk_widget_set_size_request (image17, 24, 672);

  image21 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed5), image21, 16, 0);
  gtk_widget_set_size_request (image21, 584, 40);

  YZ_label19 = gtk_label_new (_("Types de transport"));
  gtk_widget_show (YZ_label19);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label19, 32, 176);
  gtk_widget_set_size_request (YZ_label19, 205, 17);

  YZ_label20 = gtk_label_new (_("Numero de place "));
  gtk_widget_show (YZ_label20);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label20, 96, 240);
  gtk_widget_set_size_request (YZ_label20, 184, 17);

  YZ_label21 = gtk_label_new (_("Numero de matricule"));
  gtk_widget_show (YZ_label21);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label21, 0, 304);
  gtk_widget_set_size_request (YZ_label21, 198, 17);

  YZ_label22 = gtk_label_new (_("Type de service"));
  gtk_widget_show (YZ_label22);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label22, 72, 376);
  gtk_widget_set_size_request (YZ_label22, 159, 17);

  image19 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed5), image19, 0, 584);
  gtk_widget_set_size_request (image19, 600, 88);

  image20 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed5), image20, 0, 0);
  gtk_widget_set_size_request (image20, 24, 584);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed5), button6, 472, 528);
  gtk_widget_set_size_request (button6, 106, 29);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button6), alignment21);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox17);

  image58 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox17), image58, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox17), label54, FALSE, FALSE, 0);

  image16 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed5), image16, 40, 104);
  gtk_widget_set_size_request (image16, 21, 21);

  YZ_label18 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label18);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label18, 32, 104);
  gtk_widget_set_size_request (YZ_label18, 141, 17);

  YZ_label23 = gtk_label_new (_("Param\303\250tres"));
  gtk_widget_show (YZ_label23);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_label23, 456, 32);
  gtk_widget_set_size_request (YZ_label23, 145, 40);

  image22 = gtk_image_new_from_icon_name ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed5), image22, 456, 32);
  gtk_widget_set_size_request (image22, 136, 72);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed5), button14, 488, 88);
  gtk_widget_set_size_request (button14, 72, 40);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button14), alignment29);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox25);

  image66 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox25), image66, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox25), label68, FALSE, FALSE, 0);

  YZ_radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Premium"));
  gtk_widget_show (YZ_radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_radiobutton1, 200, 448);
  gtk_widget_set_size_request (YZ_radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (YZ_radiobutton1), YZ_radiobutton1_group);
  YZ_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (YZ_radiobutton1));

  YZ_checkbutton2 = gtk_check_button_new_with_mnemonic (_("Handicap"));
  gtk_widget_show (YZ_checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_checkbutton2, 272, 552);
  gtk_widget_set_size_request (YZ_checkbutton2, 118, 24);

  YZ_checkbutton1 = gtk_check_button_new_with_mnemonic (_("Presidentielle"));
  gtk_widget_show (YZ_checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_checkbutton1, 272, 512);
  gtk_widget_set_size_request (YZ_checkbutton1, 118, 24);

  YZ_radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Normal"));
  gtk_widget_show (YZ_radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed5), YZ_radiobutton2, 352, 448);
  gtk_widget_set_size_request (YZ_radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (YZ_radiobutton2), YZ_radiobutton1_group);
  YZ_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (YZ_radiobutton2));

  YZ_label8 = gtk_label_new (_("Modifier"));
  gtk_widget_show (YZ_label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), YZ_label8);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entry_id_service3 = gtk_entry_new ();
  gtk_widget_show (entry_id_service3);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_id_service3, 184, 96);
  gtk_widget_set_size_request (entry_id_service3, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service3), 8226);

  image32 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed8), image32, 0, 0);
  gtk_widget_set_size_request (image32, 632, 64);

  image30 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed8), image30, 88, 112);
  gtk_widget_set_size_request (image30, 21, 21);

  YZ_label35 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (YZ_label35);
  gtk_fixed_put (GTK_FIXED (fixed8), YZ_label35, 464, 72);
  gtk_widget_set_size_request (YZ_label35, 92, 17);

  YZ_label32 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label32);
  gtk_fixed_put (GTK_FIXED (fixed8), YZ_label32, 72, 112);
  gtk_widget_set_size_request (YZ_label32, 141, 17);

  image33 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed8), image33, 552, 64);
  gtk_widget_set_size_request (image33, 80, 232);

  image31 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed8), image31, -8, 208);
  gtk_widget_set_size_request (image31, 640, 456);

  image34 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed8), image34, 0, 64);
  gtk_widget_set_size_request (image34, 72, 232);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed8), button7, 384, 168);
  gtk_widget_set_size_request (button7, 116, 29);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button7), alignment22);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox18);

  image59 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox18), image59, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox18), label55, FALSE, FALSE, 0);

  YZ_label9 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (YZ_label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), YZ_label9);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entry_id_service1 = gtk_entry_new ();
  gtk_widget_show (entry_id_service1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_id_service1, 168, 88);
  gtk_widget_set_size_request (entry_id_service1, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_service1), 8226);

  image23 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed7), image23, 48, 104);
  gtk_widget_set_size_request (image23, 35, 21);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox1, 216, 152);
  gtk_widget_set_size_request (eventbox1, 227, 36);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_container_add (GTK_CONTAINER (eventbox1), combobox3);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Voiture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Velo "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Moto"));

  entry_matricule1 = gtk_entry_new ();
  gtk_widget_show (entry_matricule1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_matricule1, 176, 272);
  gtk_widget_set_size_request (entry_matricule1, 304, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_matricule1), 8226);

  YZ_label26 = gtk_label_new (_("Types de transport"));
  gtk_widget_show (YZ_label26);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label26, 40, 160);
  gtk_widget_set_size_request (YZ_label26, 205, 17);

  YZ_label27 = gtk_label_new (_("Numero de place "));
  gtk_widget_show (YZ_label27);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label27, 120, 224);
  gtk_widget_set_size_request (YZ_label27, 184, 17);

  YZ_label28 = gtk_label_new (_("Numero de matricule"));
  gtk_widget_show (YZ_label28);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label28, 0, 288);
  gtk_widget_set_size_request (YZ_label28, 198, 17);

  image26 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed7), image26, -16, 0);
  gtk_widget_set_size_request (image26, 40, 664);

  image27 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed7), image27, 24, 576);
  gtk_widget_set_size_request (image27, 568, 88);

  image28 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed7), image28, 592, 0);
  gtk_widget_set_size_request (image28, 32, 664);

  image25 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed7), image25, 448, 56);
  gtk_widget_set_size_request (image25, 21, 21);

  YZ_label31 = gtk_label_new (_("Page d'Acceuil"));
  gtk_widget_show (YZ_label31);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label31, 456, 48);
  gtk_widget_set_size_request (YZ_label31, 128, 32);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox2, 216, 336);
  gtk_widget_set_size_request (eventbox2, 232, 40);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_container_add (GTK_CONTAINER (eventbox2), combobox4);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Borne de charge pour voiture \303\251lectrique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Lavage "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Maintenance"));

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment9);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment9, 280, 216);
  gtk_widget_set_size_request (alignment9, 96, 32);

  spinButton_place2_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinButton_place2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinButton_place2_adj), 1, 0);
  gtk_widget_show (spinButton_place2);
  gtk_container_add (GTK_CONTAINER (alignment9), spinButton_place2);
  gtk_widget_set_size_request (spinButton_place2, 96, 32);

  YZ_label25 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label25);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label25, 48, 104);
  gtk_widget_set_size_request (YZ_label25, 141, 17);

  YZ_label29 = gtk_label_new (_("Type de service"));
  gtk_widget_show (YZ_label29);
  gtk_fixed_put (GTK_FIXED (fixed7), YZ_label29, 72, 352);
  gtk_widget_set_size_request (YZ_label29, 159, 17);

  image29 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed7), image29, 24, 0);
  gtk_widget_set_size_request (image29, 568, 56);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 448, 528);
  gtk_widget_set_size_request (button8, 120, 29);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button8), alignment23);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox19);

  image60 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox19), image60, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox19), label56, FALSE, FALSE, 0);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Normal"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton4, 344, 416);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), YZ_radiobutton1_group);
  YZ_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Premium"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton3, 208, 416);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), YZ_radiobutton1_group);
  YZ_radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Presidentielle"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbutton3, 272, 480);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Handicap"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbutton4, 272, 512);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  YZ_label10 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (YZ_label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), YZ_label10);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  YZ_entry11 = gtk_entry_new ();
  gtk_widget_show (YZ_entry11);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_entry11, 168, 88);
  gtk_widget_set_size_request (YZ_entry11, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (YZ_entry11), 8226);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry5, 216, 144);
  gtk_widget_set_size_request (comboboxentry5, 232, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Borne de charge pour voiture \303\251lectrique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Lavage "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Maintenance"));

  YZ_label37 = gtk_label_new (_("Type de service"));
  gtk_widget_show (YZ_label37);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_label37, 72, 160);
  gtk_widget_set_size_request (YZ_label37, 159, 17);

  YZ_label36 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label36);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_label36, 56, 96);
  gtk_widget_set_size_request (YZ_label36, 141, 17);

  image36 = gtk_image_new_from_icon_name ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed9), image36, 72, 96);
  gtk_widget_set_size_request (image36, 21, 21);

  image39 = gtk_image_new_from_icon_name ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed9), image39, 440, 40);
  gtk_widget_set_size_request (image39, 21, 21);

  YZ_label39 = gtk_label_new (_("R\303\251servation"));
  gtk_widget_show (YZ_label39);
  gtk_fixed_put (GTK_FIXED (fixed9), YZ_label39, 464, 40);
  gtk_widget_set_size_request (YZ_label39, 91, 17);

  image47 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image47);
  gtk_fixed_put (GTK_FIXED (fixed9), image47, 64, 0);
  gtk_widget_set_size_request (image47, 496, 40);

  image44 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image44);
  gtk_fixed_put (GTK_FIXED (fixed9), image44, 0, 240);
  gtk_widget_set_size_request (image44, 624, 424);

  image45 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image45);
  gtk_fixed_put (GTK_FIXED (fixed9), image45, 560, 0);
  gtk_widget_set_size_request (image45, 61, 240);

  image46 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image46);
  gtk_fixed_put (GTK_FIXED (fixed9), image46, 0, 0);
  gtk_widget_set_size_request (image46, 64, 240);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed9), button10, 344, 200);
  gtk_widget_set_size_request (button10, 120, 29);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button10), alignment25);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox21);

  image62 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox21), image62, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("R\303\251server"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox21), label58, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed9), button9, 208, 200);
  gtk_widget_set_size_request (button9, 127, 29);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button9), alignment24);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox20);

  image61 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_box_pack_start (GTK_BOX (hbox20), image61, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox20), label57, FALSE, FALSE, 0);

  YZ_label11 = gtk_label_new (_("R\303\251servation service"));
  gtk_widget_show (YZ_label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), YZ_label11);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  YZ_entry12 = gtk_entry_new ();
  gtk_widget_show (YZ_entry12);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_entry12, 168, 96);
  gtk_widget_set_size_request (YZ_entry12, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (YZ_entry12), 8226);

  YZ_entry13 = gtk_entry_new ();
  gtk_widget_show (YZ_entry13);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_entry13, 168, 160);
  gtk_widget_set_size_request (YZ_entry13, 312, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (YZ_entry13), 8226);

  image40 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed10), image40, 56, 104);
  gtk_widget_set_size_request (image40, 21, 21);

  YZ_label42 = gtk_label_new (_("ID service"));
  gtk_widget_show (YZ_label42);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_label42, 48, 104);
  gtk_widget_set_size_request (YZ_label42, 141, 17);

  lYZ_abel44 = gtk_label_new (_("ID r\303\251servation"));
  gtk_widget_show (lYZ_abel44);
  gtk_fixed_put (GTK_FIXED (fixed10), lYZ_abel44, 48, 168);
  gtk_widget_set_size_request (lYZ_abel44, 141, 17);

  image43 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_fixed_put (GTK_FIXED (fixed10), image43, 424, 56);
  gtk_widget_set_size_request (image43, 21, 21);

  image48 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image48);
  gtk_fixed_put (GTK_FIXED (fixed10), image48, -8, 280);
  gtk_widget_set_size_request (image48, 640, 384);

  YZ_label45 = gtk_label_new (_("Affectation"));
  gtk_widget_show (YZ_label45);
  gtk_fixed_put (GTK_FIXED (fixed10), YZ_label45, 432, 56);
  gtk_widget_set_size_request (YZ_label45, 107, 17);

  image50 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image50);
  gtk_fixed_put (GTK_FIXED (fixed10), image50, 0, 0);
  gtk_widget_set_size_request (image50, 56, 280);

  image49 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image49);
  gtk_fixed_put (GTK_FIXED (fixed10), image49, 568, 0);
  gtk_widget_set_size_request (image49, 56, 280);

  image51 = create_pixmap (window3, "Firefox_wallpaper.png");
  gtk_widget_show (image51);
  gtk_fixed_put (GTK_FIXED (fixed10), image51, 56, 0);
  gtk_widget_set_size_request (image51, 512, 56);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed10), button12, 344, 224);
  gtk_widget_set_size_request (button12, 123, 29);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button12), alignment27);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox23);

  image64 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox23), image64, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("R\303\251frecher"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox23), label60, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed10), button11, 192, 224);
  gtk_widget_set_size_request (button11, 125, 29);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button11), alignment26);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox22);

  image63 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_box_pack_start (GTK_BOX (hbox22), image63, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox22), label59, FALSE, FALSE, 0);

  YZ_label12 = gtk_label_new (_("Affectation"));
  gtk_widget_show (YZ_label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), YZ_label12);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) YZ_radiobutton1, "toggled",
                    G_CALLBACK (on_YZ_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) YZ_checkbutton2, "toggled",
                    G_CALLBACK (on_YZ_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) YZ_checkbutton1, "toggled",
                    G_CALLBACK (on_YZ_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) YZ_radiobutton2, "toggled",
                    G_CALLBACK (on_YZ_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window3, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window3, image8, "image8");
  GLADE_HOOKUP_OBJECT (window3, image12, "image12");
  GLADE_HOOKUP_OBJECT (window3, image15, "image15");
  GLADE_HOOKUP_OBJECT (window3, image13, "image13");
  GLADE_HOOKUP_OBJECT (window3, image14, "image14");
  GLADE_HOOKUP_OBJECT (window3, Yz_ID_service, "Yz_ID_service");
  GLADE_HOOKUP_OBJECT (window3, button2, "button2");
  GLADE_HOOKUP_OBJECT (window3, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window3, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window3, image54, "image54");
  GLADE_HOOKUP_OBJECT (window3, label50, "label50");
  GLADE_HOOKUP_OBJECT (window3, button3, "button3");
  GLADE_HOOKUP_OBJECT (window3, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window3, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window3, image55, "image55");
  GLADE_HOOKUP_OBJECT (window3, label51, "label51");
  GLADE_HOOKUP_OBJECT (window3, button4, "button4");
  GLADE_HOOKUP_OBJECT (window3, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window3, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window3, image56, "image56");
  GLADE_HOOKUP_OBJECT (window3, label52, "label52");
  GLADE_HOOKUP_OBJECT (window3, button5, "button5");
  GLADE_HOOKUP_OBJECT (window3, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window3, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window3, image57, "image57");
  GLADE_HOOKUP_OBJECT (window3, label53, "label53");
  GLADE_HOOKUP_OBJECT (window3, YZ_label7, "YZ_label7");
  GLADE_HOOKUP_OBJECT (window3, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window3, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window3, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window3, spinButton_place, "spinButton_place");
  GLADE_HOOKUP_OBJECT (window3, entry_id_service, "entry_id_service");
  GLADE_HOOKUP_OBJECT (window3, entry_matricule, "entry_matricule");
  GLADE_HOOKUP_OBJECT (window3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window3, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (window3, image17, "image17");
  GLADE_HOOKUP_OBJECT (window3, image21, "image21");
  GLADE_HOOKUP_OBJECT (window3, YZ_label19, "YZ_label19");
  GLADE_HOOKUP_OBJECT (window3, YZ_label20, "YZ_label20");
  GLADE_HOOKUP_OBJECT (window3, YZ_label21, "YZ_label21");
  GLADE_HOOKUP_OBJECT (window3, YZ_label22, "YZ_label22");
  GLADE_HOOKUP_OBJECT (window3, image19, "image19");
  GLADE_HOOKUP_OBJECT (window3, image20, "image20");
  GLADE_HOOKUP_OBJECT (window3, button6, "button6");
  GLADE_HOOKUP_OBJECT (window3, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window3, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window3, image58, "image58");
  GLADE_HOOKUP_OBJECT (window3, label54, "label54");
  GLADE_HOOKUP_OBJECT (window3, image16, "image16");
  GLADE_HOOKUP_OBJECT (window3, YZ_label18, "YZ_label18");
  GLADE_HOOKUP_OBJECT (window3, YZ_label23, "YZ_label23");
  GLADE_HOOKUP_OBJECT (window3, image22, "image22");
  GLADE_HOOKUP_OBJECT (window3, button14, "button14");
  GLADE_HOOKUP_OBJECT (window3, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window3, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window3, image66, "image66");
  GLADE_HOOKUP_OBJECT (window3, label68, "label68");
  GLADE_HOOKUP_OBJECT (window3, YZ_radiobutton1, "YZ_radiobutton1");
  GLADE_HOOKUP_OBJECT (window3, YZ_checkbutton2, "YZ_checkbutton2");
  GLADE_HOOKUP_OBJECT (window3, YZ_checkbutton1, "YZ_checkbutton1");
  GLADE_HOOKUP_OBJECT (window3, YZ_radiobutton2, "YZ_radiobutton2");
  GLADE_HOOKUP_OBJECT (window3, YZ_label8, "YZ_label8");
  GLADE_HOOKUP_OBJECT (window3, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window3, entry_id_service3, "entry_id_service3");
  GLADE_HOOKUP_OBJECT (window3, image32, "image32");
  GLADE_HOOKUP_OBJECT (window3, image30, "image30");
  GLADE_HOOKUP_OBJECT (window3, YZ_label35, "YZ_label35");
  GLADE_HOOKUP_OBJECT (window3, YZ_label32, "YZ_label32");
  GLADE_HOOKUP_OBJECT (window3, image33, "image33");
  GLADE_HOOKUP_OBJECT (window3, image31, "image31");
  GLADE_HOOKUP_OBJECT (window3, image34, "image34");
  GLADE_HOOKUP_OBJECT (window3, button7, "button7");
  GLADE_HOOKUP_OBJECT (window3, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window3, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window3, image59, "image59");
  GLADE_HOOKUP_OBJECT (window3, label55, "label55");
  GLADE_HOOKUP_OBJECT (window3, YZ_label9, "YZ_label9");
  GLADE_HOOKUP_OBJECT (window3, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window3, entry_id_service1, "entry_id_service1");
  GLADE_HOOKUP_OBJECT (window3, image23, "image23");
  GLADE_HOOKUP_OBJECT (window3, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window3, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (window3, entry_matricule1, "entry_matricule1");
  GLADE_HOOKUP_OBJECT (window3, YZ_label26, "YZ_label26");
  GLADE_HOOKUP_OBJECT (window3, YZ_label27, "YZ_label27");
  GLADE_HOOKUP_OBJECT (window3, YZ_label28, "YZ_label28");
  GLADE_HOOKUP_OBJECT (window3, image26, "image26");
  GLADE_HOOKUP_OBJECT (window3, image27, "image27");
  GLADE_HOOKUP_OBJECT (window3, image28, "image28");
  GLADE_HOOKUP_OBJECT (window3, image25, "image25");
  GLADE_HOOKUP_OBJECT (window3, YZ_label31, "YZ_label31");
  GLADE_HOOKUP_OBJECT (window3, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (window3, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (window3, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window3, spinButton_place2, "spinButton_place2");
  GLADE_HOOKUP_OBJECT (window3, YZ_label25, "YZ_label25");
  GLADE_HOOKUP_OBJECT (window3, YZ_label29, "YZ_label29");
  GLADE_HOOKUP_OBJECT (window3, image29, "image29");
  GLADE_HOOKUP_OBJECT (window3, button8, "button8");
  GLADE_HOOKUP_OBJECT (window3, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window3, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window3, image60, "image60");
  GLADE_HOOKUP_OBJECT (window3, label56, "label56");
  GLADE_HOOKUP_OBJECT (window3, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window3, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window3, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window3, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window3, YZ_label10, "YZ_label10");
  GLADE_HOOKUP_OBJECT (window3, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window3, YZ_entry11, "YZ_entry11");
  GLADE_HOOKUP_OBJECT (window3, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (window3, YZ_label37, "YZ_label37");
  GLADE_HOOKUP_OBJECT (window3, YZ_label36, "YZ_label36");
  GLADE_HOOKUP_OBJECT (window3, image36, "image36");
  GLADE_HOOKUP_OBJECT (window3, image39, "image39");
  GLADE_HOOKUP_OBJECT (window3, YZ_label39, "YZ_label39");
  GLADE_HOOKUP_OBJECT (window3, image47, "image47");
  GLADE_HOOKUP_OBJECT (window3, image44, "image44");
  GLADE_HOOKUP_OBJECT (window3, image45, "image45");
  GLADE_HOOKUP_OBJECT (window3, image46, "image46");
  GLADE_HOOKUP_OBJECT (window3, button10, "button10");
  GLADE_HOOKUP_OBJECT (window3, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window3, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window3, image62, "image62");
  GLADE_HOOKUP_OBJECT (window3, label58, "label58");
  GLADE_HOOKUP_OBJECT (window3, button9, "button9");
  GLADE_HOOKUP_OBJECT (window3, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window3, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window3, image61, "image61");
  GLADE_HOOKUP_OBJECT (window3, label57, "label57");
  GLADE_HOOKUP_OBJECT (window3, YZ_label11, "YZ_label11");
  GLADE_HOOKUP_OBJECT (window3, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window3, YZ_entry12, "YZ_entry12");
  GLADE_HOOKUP_OBJECT (window3, YZ_entry13, "YZ_entry13");
  GLADE_HOOKUP_OBJECT (window3, image40, "image40");
  GLADE_HOOKUP_OBJECT (window3, YZ_label42, "YZ_label42");
  GLADE_HOOKUP_OBJECT (window3, lYZ_abel44, "lYZ_abel44");
  GLADE_HOOKUP_OBJECT (window3, image43, "image43");
  GLADE_HOOKUP_OBJECT (window3, image48, "image48");
  GLADE_HOOKUP_OBJECT (window3, YZ_label45, "YZ_label45");
  GLADE_HOOKUP_OBJECT (window3, image50, "image50");
  GLADE_HOOKUP_OBJECT (window3, image49, "image49");
  GLADE_HOOKUP_OBJECT (window3, image51, "image51");
  GLADE_HOOKUP_OBJECT (window3, button12, "button12");
  GLADE_HOOKUP_OBJECT (window3, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window3, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window3, image64, "image64");
  GLADE_HOOKUP_OBJECT (window3, label60, "label60");
  GLADE_HOOKUP_OBJECT (window3, button11, "button11");
  GLADE_HOOKUP_OBJECT (window3, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window3, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window3, image63, "image63");
  GLADE_HOOKUP_OBJECT (window3, label59, "label59");
  GLADE_HOOKUP_OBJECT (window3, YZ_label12, "YZ_label12");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed11;
  GtkWidget *entry_Nom;
  GtkWidget *entry_Prenom;
  GtkWidget *entry_Username;
  GtkWidget *entry_Password;
  GtkWidget *label66;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *button13;
  GtkWidget *alignment28;
  GtkWidget *hbox24;
  GtkWidget *image65;
  GtkWidget *label67;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window4), fixed11);

  entry_Nom = gtk_entry_new ();
  gtk_widget_show (entry_Nom);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Nom, 120, 80);
  gtk_widget_set_size_request (entry_Nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Nom), 8226);

  entry_Prenom = gtk_entry_new ();
  gtk_widget_show (entry_Prenom);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Prenom, 120, 112);
  gtk_widget_set_size_request (entry_Prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Prenom), 8226);

  entry_Username = gtk_entry_new ();
  gtk_widget_show (entry_Username);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Username, 120, 144);
  gtk_widget_set_size_request (entry_Username, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Username), 8226);

  entry_Password = gtk_entry_new ();
  gtk_widget_show (entry_Password);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_Password, 120, 176);
  gtk_widget_set_size_request (entry_Password, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Password), 8226);

  label66 = gtk_label_new (_("Inscription"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed11), label66, 144, 48);
  gtk_widget_set_size_request (label66, 111, 17);

  label61 = gtk_label_new (_("Nom"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed11), label61, 64, 88);
  gtk_widget_set_size_request (label61, 49, 17);

  label62 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed11), label62, 56, 120);
  gtk_widget_set_size_request (label62, 63, 17);

  label63 = gtk_label_new (_("Username"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed11), label63, 24, 152);
  gtk_widget_set_size_request (label63, 112, 16);

  label64 = gtk_label_new (_("Password"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed11), label64, 40, 184);
  gtk_widget_set_size_request (label64, 87, 17);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed11), button13, 160, 208);
  gtk_widget_set_size_request (button13, 90, 32);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button13), alignment28);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox24);

  image65 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox24), image65, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox24), label67, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window4, entry_Nom, "entry_Nom");
  GLADE_HOOKUP_OBJECT (window4, entry_Prenom, "entry_Prenom");
  GLADE_HOOKUP_OBJECT (window4, entry_Username, "entry_Username");
  GLADE_HOOKUP_OBJECT (window4, entry_Password, "entry_Password");
  GLADE_HOOKUP_OBJECT (window4, label66, "label66");
  GLADE_HOOKUP_OBJECT (window4, label61, "label61");
  GLADE_HOOKUP_OBJECT (window4, label62, "label62");
  GLADE_HOOKUP_OBJECT (window4, label63, "label63");
  GLADE_HOOKUP_OBJECT (window4, label64, "label64");
  GLADE_HOOKUP_OBJECT (window4, button13, "button13");
  GLADE_HOOKUP_OBJECT (window4, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window4, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window4, image65, "image65");
  GLADE_HOOKUP_OBJECT (window4, label67, "label67");

  return window4;
}

